In [1]:
import numpy as np

In [11]:
array1 = np.zeros(15)
print("Ejercicio 1:")
print(array1)

Ejercicio 1:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
array2 = np.arange(1, 41)
print("Ejercicio 2:")
print(array2)

Ejercicio 2:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]


In [4]:
array3 = np.arange(2, 51, 2)
print("Ejercicio 3:")
print(array3)

Ejercicio 3:
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


In [3]:
array4 = np.arange(1, 101, 2)
print(array4)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [4]:
matriz5 = np.random.rand(4, 4)
print(matriz5)

[[0.34519968 0.98515748 0.69944088 0.03514108]
 [0.60430655 0.0172533  0.87839763 0.72145835]
 [0.19903997 0.81413978 0.6300111  0.74775997]
 [0.00754223 0.79600547 0.12917169 0.73282181]]


In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

suma = a + b
print(suma)

[5 7 9]


In [7]:
matrizA = np.random.randint(1, 11, (3, 3))
matrizB = np.random.randint(1, 11, (3, 3))

resultado = np.dot(matrizA, matrizB)

print("Matriz A:\n", matrizA)
print("Matriz B:\n", matrizB)
print("Resultado:\n", resultado)

Matriz A:
 [[ 4  5  9]
 [ 9  6  6]
 [ 6 10  9]]
Matriz B:
 [[ 4  3  5]
 [ 5  7  7]
 [ 8  6 10]]
Resultado:
 [[113 101 145]
 [114 105 147]
 [146 142 190]]


In [8]:
array8 = np.random.randint(1, 101, 15)

print("Array:", array8)
print("Máximo:", array8.max())
print("Mínimo:", array8.min())
print("Promedio:", array8.mean())

Array: [71 24 37 78 26 18 50 52 70 88 90 62 44 21 64]
Máximo: 90
Mínimo: 18
Promedio: 53.0


In [9]:
matriz9 = np.arange(1, 26).reshape(5, 5)

diagonal = np.diag(matriz9)

print("Matriz:\n", matriz9)
print("Diagonal:", diagonal)

Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


In [10]:
matriz10 = np.random.randint(1, 21, (5, 5))

suma_filas = matriz10.sum(axis=1)
suma_columnas = matriz10.sum(axis=0)

print("Matriz:\n", matriz10)
print("Suma de filas:", suma_filas)
print("Suma de columnas:", suma_columnas)

Matriz:
 [[15 13 14  5 14]
 [18 17  9  7 16]
 [14 11 20 19  7]
 [20 14 16 17  7]
 [ 1 17 17  6 17]]
Suma de filas: [61 67 71 74 58]
Suma de columnas: [68 72 76 54 61]


In [ ]:
# prueba de cambio para git